### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by danmoser** [ContinuumIO/pycosat#34]
`$ sudo pip install pycosat`

> Collecting pycosat
  Using cached https://files.pythonhosted.org/packages/c0/fd/e38d68774c0a345b0090d608a90f1fbf423970d812f7ec7aef9ac024e648/pycosat-0.6.3.zip
Building wheels for collected packages: pycosat
  Building wheel for pycosat (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-1lzfi2ao/pycosat/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_9n7hgw6 --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  copying test_pycosat.py -> build/lib.linux-x86_64-3.6
  running build_ext
  building 'pycosat' extension
  creating build/temp.linux-x86_64-3.6
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c pycosat.c -o build/temp.linux-x86_64-3.6/pycosat.o
  pycosat.c:10:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ERROR: Failed building wheel for pycosat

>  Running setup.py clean for pycosat
  Failed to build pycosat

**Comment by msarahan** [comment]
Please do not ever use ``sudo pip`` - that is extremely dangerous and completely unnecessary with user installs of miniconda or anaconda.

Is there any reason why you can't just use ``conda install pycosat``?

**Comment by danmoser** [comment]
Thanks for the tip about `sudo pip`. I always avoid it.

`conda install pycosat` gave the same error. However, I discovered how to solve it. Apparently, it was a bad previous installation with x86_64 compilation... I removed the contents of `$HOME/.local/lib/python2.7/site-packages/pycosat-0.6.3.dist-info` and the file `$HOME/.local/lib/python2.7/site-packages/pycosat.so` and it worked!!

Thanks!

**Comment by walter-sharethis** [comment]
For Ubuntu/Pop-OS: pycosat needs header files from python dev packages.  Run:
`sudo apt-get install python3-dev`
Note that older posts on this issue - which has been around for 5 years - say to install python-dev, which is the wrong thing to do unless you are still using python2.
